on:
  push:
    branches:
      - main

jobs:
  hello_job:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: say hello
        run: |
          echo "hello"
          echo "world"
          echo "running on: ${{ matrix.os }}"
    
